version: '3.8'

services:
  dos-monitor:
    build: .
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    volumes:
      - ./database:/var/www/database
      - ./storage:/var/www/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/dos-monitor"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development version with hot reload
  dos-monitor-dev:
    build: .
    ports:
      - "8001:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    volumes:
      - .:/var/www
      - ./database:/var/www/database
      - ./storage:/var/www/storage
    restart: unless-stopped
    profiles:
      - dev

  # Production with MySQL
  dos-monitor-mysql:
    build: .
    ports:
      - "8002:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=dos_monitor
      - DB_USERNAME=dos_user
      - DB_PASSWORD=dos_password
    volumes:
      - ./storage:/var/www/storage
    depends_on:
      - mysql
    restart: unless-stopped
    profiles:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: dos_monitor
      MYSQL_USER: dos_user
      MYSQL_PASSWORD: dos_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    profiles:
      - mysql

volumes:
  mysql_data: